"""execution models

Revision ID: 3a1cf533642c
Revises: 1df343a1dca3
Create Date: 2026-07-17 12:48:28.920811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = '3a1cf533642c'
down_revision: Union[str, Sequence[str], None] = '1df343a1dca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('benchmark_version_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_by_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'TIMED_OUT', name='execution_status'), nullable=False),
    sa.Column('target_model', sa.String(length=255), nullable=False),
    sa.Column('execution_config', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('benchmark_hash', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_version_id'], ['benchmark_versions.id'], name=op.f('fk_executions_benchmark_version_id_benchmark_versions')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_executions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_executions_project_id_projects')),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['organization_members.id'], name=op.f('fk_executions_submitted_by_id_organization_members')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_executions_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions'))
    )
    op.drop_table('evaluation_sessions')
    op.drop_table('atlas_runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atlas_runs',
    sa.Column('session_id', sa.NUMERIC(), nullable=False),
    sa.Column('benchmark_version_id', sa.CHAR(length=32), nullable=False),
    sa.Column('adapter_version_id', sa.CHAR(length=32), nullable=False),
    sa.Column('target_model', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by_id', sa.NUMERIC(), nullable=True),
    sa.Column('updated_by_id', sa.NUMERIC(), nullable=True),
    sa.Column('archived_at', sa.DATETIME(), nullable=True),
    sa.Column('version_number', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['adapter_version_id'], ['execution_adapter_versions.id'], name=op.f('fk_atlas_runs_adapter_version_id_execution_adapter_versions')),
    sa.ForeignKeyConstraint(['benchmark_version_id'], ['benchmark_versions.id'], name=op.f('fk_atlas_runs_benchmark_version_id_benchmark_versions')),
    sa.ForeignKeyConstraint(['session_id'], ['evaluation_sessions.id'], name=op.f('fk_atlas_runs_session_id_evaluation_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atlas_runs'))
    )
    op.create_table('evaluation_sessions',
    sa.Column('project_id', sa.NUMERIC(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by_id', sa.NUMERIC(), nullable=True),
    sa.Column('updated_by_id', sa.NUMERIC(), nullable=True),
    sa.Column('archived_at', sa.DATETIME(), nullable=True),
    sa.Column('version_number', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_evaluation_sessions_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_sessions'))
    )
    op.drop_table('executions')
    # ### end Alembic commands ###
