"""execution models

Revision ID: 3a1cf533642c
Revises: 1df343a1dca3
Create Date: 2026-07-17 12:48:28.920811

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3a1cf533642c"
down_revision: str | Sequence[str] | None = "1df343a1dca3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "executions",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("benchmark_version_id", sa.Uuid(), nullable=False),
        sa.Column("submitted_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "DRAFT",
                "QUEUED",
                "SCHEDULED",
                "STARTING",
                "RUNNING",
                "EVALUATING",
                "COMPLETED",
                "FAILED",
                "RETRYING",
                "CANCELLING",
                "CANCELLED",
                "TIMED_OUT",
                name="execution_status",
            ),
            nullable=False,
        ),
        sa.Column("target_model", sa.String(length=255), nullable=False),
        sa.Column("execution_config", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("benchmark_hash", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["benchmark_version_id"],
            ["benchmark_versions.id"],
            name=op.f("fk_executions_benchmark_version_id_benchmark_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_executions_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_executions_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_id"],
            ["organization_members.id"],
            name=op.f("fk_executions_submitted_by_id_organization_members"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_executions_updated_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_executions")),
    )
    # Handle report_versions dependencies
    with op.batch_alter_table("report_versions") as batch_op:
        batch_op.drop_constraint(
            "fk_report_versions_evaluation_session_id_evaluation_sessions", type_="foreignkey"
        )
        batch_op.drop_column("evaluation_session_id")
        batch_op.add_column(sa.Column("execution_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            op.f("fk_report_versions_execution_id_executions"),
            "executions",
            ["execution_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # [HISTORICAL MIGRATION REWRITE - Dockerization Fix]
    # Why this edit was necessary:
    # Alembic autogenerate missed dropping these incoming foreign key constraints from
    # tables created in parallel branches (`atlas_tasks`, etc.) and earlier branches.
    # Postgres forbids dropping a table that is referenced by FKs. We explicitly
    # drop them here before dropping `atlas_runs`.

    with op.batch_alter_table("model_outputs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_model_outputs_atlas_run_id_atlas_runs", type_="foreignkey")
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.drop_constraint("fk_artifacts_atlas_run_id_atlas_runs", type_="foreignkey")
    with op.batch_alter_table("capability_profiles", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_capability_profiles_atlas_run_id_atlas_runs", type_="foreignkey"
        )
    with op.batch_alter_table("atlas_tasks", schema=None) as batch_op:
        batch_op.drop_constraint("fk_atlas_tasks_atlas_run_id_atlas_runs", type_="foreignkey")
    with op.batch_alter_table("run_events", schema=None) as batch_op:
        batch_op.drop_constraint("fk_run_events_atlas_run_id_atlas_runs", type_="foreignkey")

    op.drop_table("atlas_runs")
    op.drop_table("evaluation_sessions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "atlas_runs",
        sa.Column("session_id", sa.NUMERIC(), nullable=False),
        sa.Column("benchmark_version_id", sa.CHAR(length=32), nullable=False),
        sa.Column("adapter_version_id", sa.CHAR(length=32), nullable=False),
        sa.Column("target_model", sa.VARCHAR(length=255), nullable=False),
        sa.Column("status", sa.VARCHAR(length=9), nullable=False),
        sa.Column("started_at", sa.DATETIME(), nullable=True),
        sa.Column("completed_at", sa.DATETIME(), nullable=True),
        sa.Column("id", sa.NUMERIC(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.Column("created_by_id", sa.NUMERIC(), nullable=True),
        sa.Column("updated_by_id", sa.NUMERIC(), nullable=True),
        sa.Column("archived_at", sa.DATETIME(), nullable=True),
        sa.Column("version_number", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["adapter_version_id"],
            ["execution_adapter_versions.id"],
            name=op.f("fk_atlas_runs_adapter_version_id_execution_adapter_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["benchmark_version_id"],
            ["benchmark_versions.id"],
            name=op.f("fk_atlas_runs_benchmark_version_id_benchmark_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["evaluation_sessions.id"],
            name=op.f("fk_atlas_runs_session_id_evaluation_sessions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_atlas_runs")),
    )
    op.create_table(
        "evaluation_sessions",
        sa.Column("project_id", sa.NUMERIC(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("started_at", sa.DATETIME(), nullable=True),
        sa.Column("completed_at", sa.DATETIME(), nullable=True),
        sa.Column("id", sa.NUMERIC(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.Column("created_by_id", sa.NUMERIC(), nullable=True),
        sa.Column("updated_by_id", sa.NUMERIC(), nullable=True),
        sa.Column("archived_at", sa.DATETIME(), nullable=True),
        sa.Column("version_number", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_evaluation_sessions_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_sessions")),
    )
    # [HISTORICAL MIGRATION REWRITE - Dockerization Fix]
    # Recreate the constraints we dropped in upgrade()
    with op.batch_alter_table("model_outputs", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_model_outputs_atlas_run_id_atlas_runs", "atlas_runs", ["atlas_run_id"], ["id"]
        )
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_artifacts_atlas_run_id_atlas_runs", "atlas_runs", ["atlas_run_id"], ["id"]
        )
    with op.batch_alter_table("capability_profiles", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_capability_profiles_atlas_run_id_atlas_runs", "atlas_runs", ["atlas_run_id"], ["id"]
        )
    with op.batch_alter_table("atlas_tasks", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_atlas_tasks_atlas_run_id_atlas_runs",
            "atlas_runs",
            ["atlas_run_id"],
            ["id"],
            ondelete="CASCADE",
        )
    with op.batch_alter_table("run_events", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_run_events_atlas_run_id_atlas_runs",
            "atlas_runs",
            ["atlas_run_id"],
            ["id"],
            ondelete="CASCADE",
        )

    op.drop_table("executions")

    with op.batch_alter_table("report_versions") as batch_op:
        batch_op.drop_constraint(
            op.f("fk_report_versions_execution_id_executions"), type_="foreignkey"
        )
        batch_op.drop_column("execution_id")
        batch_op.add_column(sa.Column("evaluation_session_id", sa.NUMERIC(), nullable=True))
        batch_op.create_foreign_key(
            "fk_report_versions_evaluation_session_id_evaluation_sessions",
            "evaluation_sessions",
            ["evaluation_session_id"],
            ["id"],
        )
    # ### end Alembic commands ###
