"""Initial migration

Revision ID: 4007056c9559
Revises:
Create Date: 2026-07-07 13:04:38.408370

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4007056c9559"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "benchmark_categories",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_benchmark_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_benchmark_categories_name")),
    )
    op.create_table(
        "capabilities",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capabilities")),
        sa.UniqueConstraint("name", name=op.f("uq_capabilities_name")),
    )
    op.create_table(
        "configurations",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "scope",
            postgresql.ENUM("ENV", "PROJECT", "BENCHMARK", name="configuration_scope"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_configurations")),
    )
    op.create_index(op.f("ix_configurations_key"), "configurations", ["key"], unique=True)
    op.create_table(
        "dataset_licenses",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_licenses")),
    )
    op.create_table(
        "dataset_registries",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_registries")),
    )
    op.create_table(
        "dataset_sources",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_sources")),
    )
    op.create_table(
        "evaluation_strategies",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("EXACT_MATCH", "LLM_JUDGE", "SCRIPT", name="strategy_type"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_strategies")),
        sa.UniqueConstraint("name", name=op.f("uq_evaluation_strategies_name")),
    )
    op.create_table(
        "execution_adapters",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("LOCAL", "KUBERNETES", "AWS_BATCH", name="adapter_type"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_adapters")),
        sa.UniqueConstraint("name", name=op.f("uq_execution_adapters_name")),
    )
    op.create_table(
        "judges",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("model_identifier", sa.String(length=255), nullable=False),
        sa.Column("prompt_template", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_judges")),
        sa.UniqueConstraint("name", name=op.f("uq_judges_name")),
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "datasets",
        sa.Column("registry_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("license_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["license_id"],
            ["dataset_licenses.id"],
            name=op.f("fk_datasets_license_id_dataset_licenses"),
        ),
        sa.ForeignKeyConstraint(
            ["registry_id"],
            ["dataset_registries.id"],
            name=op.f("fk_datasets_registry_id_dataset_registries"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["dataset_sources.id"],
            name=op.f("fk_datasets_source_id_dataset_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_datasets")),
    )
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_projects_org_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_users_org_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "benchmarks",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("objective", sa.String(), nullable=True),
        sa.Column("difficulty", sa.String(length=50), nullable=True),
        sa.Column("domain", sa.String(length=100), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("visibility", sa.String(length=50), nullable=True),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_benchmarks_author_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_benchmarks_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_benchmarks")),
    )
    op.create_index(op.f("ix_benchmarks_project_id"), "benchmarks", ["project_id"], unique=False)
    op.create_table(
        "configuration_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("configuration_id", sa.UUID(), nullable=False),
        sa.Column("version_string", sa.String(length=50), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["configuration_id"],
            ["configurations.id"],
            name=op.f("fk_configuration_versions_configuration_id_configurations"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_configuration_versions_created_by_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_configuration_versions")),
    )
    op.create_table(
        "dataset_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("version_string", sa.String(length=50), nullable=False),
        sa.Column("storage_path", sa.String(), nullable=False),
        sa.Column("checksum", sa.String(length=255), nullable=True),
        sa.Column(
            "validation_status",
            postgresql.ENUM("PENDING", "VALIDATED", "FAILED", name="dataset_validation_status"),
            nullable=False,
        ),
        sa.Column("schema_def", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_dataset_versions_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["datasets.id"], name=op.f("fk_dataset_versions_dataset_id_datasets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_versions")),
    )
    op.create_table(
        "evaluation_sessions",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_evaluation_sessions_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_sessions")),
    )
    op.create_index(
        op.f("ix_evaluation_sessions_project_id"),
        "evaluation_sessions",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "evaluation_strategy_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("strategy_id", sa.UUID(), nullable=False),
        sa.Column("version_string", sa.String(length=50), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_evaluation_strategy_versions_created_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["evaluation_strategies.id"],
            name=op.f("fk_evaluation_strategy_versions_strategy_id_evaluation_strategies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_strategy_versions")),
    )
    op.create_table(
        "execution_adapter_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("adapter_id", sa.UUID(), nullable=False),
        sa.Column("version_string", sa.String(length=50), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["adapter_id"],
            ["execution_adapters.id"],
            name=op.f("fk_execution_adapter_versions_adapter_id_execution_adapters"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_execution_adapter_versions_created_by_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_adapter_versions")),
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "reports",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_reports_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(op.f("ix_reports_project_id"), "reports", ["project_id"], unique=False)
    op.create_table(
        "benchmark_capability_link",
        sa.Column("benchmark_id", sa.UUID(), nullable=False),
        sa.Column("capability_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["benchmark_id"],
            ["benchmarks.id"],
            name=op.f("fk_benchmark_capability_link_benchmark_id_benchmarks"),
        ),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["capabilities.id"],
            name=op.f("fk_benchmark_capability_link_capability_id_capabilities"),
        ),
        sa.PrimaryKeyConstraint(
            "benchmark_id", "capability_id", name=op.f("pk_benchmark_capability_link")
        ),
    )
    op.create_table(
        "benchmark_category_link",
        sa.Column("benchmark_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["benchmark_id"],
            ["benchmarks.id"],
            name=op.f("fk_benchmark_category_link_benchmark_id_benchmarks"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["benchmark_categories.id"],
            name=op.f("fk_benchmark_category_link_category_id_benchmark_categories"),
        ),
        sa.PrimaryKeyConstraint(
            "benchmark_id", "category_id", name=op.f("pk_benchmark_category_link")
        ),
    )
    op.create_table(
        "benchmark_lifecycles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("benchmark_id", sa.UUID(), nullable=False),
        sa.Column(
            "state",
            postgresql.ENUM(
                "PROPOSAL",
                "DESIGN",
                "DRAFT",
                "VALIDATION",
                "REVIEW",
                "PUBLISHED",
                "ARCHIVE",
                name="benchmark_state",
            ),
            nullable=False,
        ),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["benchmark_id"],
            ["benchmarks.id"],
            name=op.f("fk_benchmark_lifecycles_benchmark_id_benchmarks"),
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_id"],
            ["users.id"],
            name=op.f("fk_benchmark_lifecycles_changed_by_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_benchmark_lifecycles")),
    )
    op.create_table(
        "benchmark_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("benchmark_id", sa.UUID(), nullable=False),
        sa.Column("version_string", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["benchmark_id"],
            ["benchmarks.id"],
            name=op.f("fk_benchmark_versions_benchmark_id_benchmarks"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_benchmark_versions_created_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_benchmark_versions")),
    )
    op.create_table(
        "report_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("version_string", sa.String(length=50), nullable=False),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("evaluation_session_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_report_versions_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_session_id"],
            ["evaluation_sessions.id"],
            name=op.f("fk_report_versions_evaluation_session_id_evaluation_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["report_id"], ["reports.id"], name=op.f("fk_report_versions_report_id_reports")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_versions")),
    )
    op.create_table(
        "atlas_runs",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("benchmark_version_id", sa.Uuid(), nullable=False),
        sa.Column("adapter_version_id", sa.Uuid(), nullable=False),
        sa.Column("target_model", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "RUNNING", "COMPLETED", "FAILED", "CANCELLED", name="run_status"
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["adapter_version_id"],
            ["execution_adapter_versions.id"],
            name=op.f("fk_atlas_runs_adapter_version_id_execution_adapter_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["benchmark_version_id"],
            ["benchmark_versions.id"],
            name=op.f("fk_atlas_runs_benchmark_version_id_benchmark_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["evaluation_sessions.id"],
            name=op.f("fk_atlas_runs_session_id_evaluation_sessions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_atlas_runs")),
    )
    op.create_index(op.f("ix_atlas_runs_session_id"), "atlas_runs", ["session_id"], unique=False)
    op.create_table(
        "report_metrics",
        sa.Column("report_version_id", sa.Uuid(), nullable=False),
        sa.Column("metric_name", sa.String(length=255), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_version_id"],
            ["report_versions.id"],
            name=op.f("fk_report_metrics_report_version_id_report_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_metrics")),
    )
    op.create_table(
        "tasks",
        sa.Column("benchmark_version_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["benchmark_version_id"],
            ["benchmark_versions.id"],
            name=op.f("fk_tasks_benchmark_version_id_benchmark_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_table(
        "artifacts",
        sa.Column("atlas_run_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "LOG",
                "LOGS",
                "WEIGHTS",
                "FILE",
                "MODEL_OUTPUT",
                "EVALUATION_RESULT",
                name="artifact_type",
            ),
            nullable=False,
        ),
        sa.Column("uri", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["atlas_run_id"], ["atlas_runs.id"], name=op.f("fk_artifacts_atlas_run_id_atlas_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
    )
    op.create_table(
        "capability_profiles",
        sa.Column("atlas_run_id", sa.UUID(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("profile_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["atlas_run_id"],
            ["atlas_runs.id"],
            name=op.f("fk_capability_profiles_atlas_run_id_atlas_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capability_profiles")),
        sa.UniqueConstraint("atlas_run_id", name=op.f("uq_capability_profiles_atlas_run_id")),
    )
    op.create_table(
        "constraints",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_constraints_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_constraints")),
    )
    op.create_table(
        "evaluation_rules",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("rule_definition", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_evaluation_rules_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_rules")),
    )
    op.create_table(
        "prompts",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("template", sa.String(), nullable=False),
        sa.Column("system_instruction", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], name=op.f("fk_prompts_task_id_tasks")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompts")),
    )
    op.create_table(
        "test_cases",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("input_data", sa.String(), nullable=False),
        sa.Column("expected_output", sa.String(), nullable=False),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_test_cases_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_cases")),
    )
    op.create_table(
        "capability_scores",
        sa.Column("capability_profile_id", sa.UUID(), nullable=False),
        sa.Column("capability_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["capabilities.id"],
            name=op.f("fk_capability_scores_capability_id_capabilities"),
        ),
        sa.ForeignKeyConstraint(
            ["capability_profile_id"],
            ["capability_profiles.id"],
            name=op.f("fk_capability_scores_capability_profile_id_capability_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capability_scores")),
    )
    op.create_table(
        "model_outputs",
        sa.Column("atlas_run_id", sa.UUID(), nullable=False),
        sa.Column("test_case_id", sa.UUID(), nullable=False),
        sa.Column("raw_output", sa.String(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["atlas_run_id"],
            ["atlas_runs.id"],
            name=op.f("fk_model_outputs_atlas_run_id_atlas_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["test_case_id"],
            ["test_cases.id"],
            name=op.f("fk_model_outputs_test_case_id_test_cases"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_outputs")),
    )
    op.create_index(
        op.f("ix_model_outputs_atlas_run_id"), "model_outputs", ["atlas_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_model_outputs_test_case_id"), "model_outputs", ["test_case_id"], unique=False
    )
    op.create_table(
        "evaluation_results",
        sa.Column("model_output_id", sa.UUID(), nullable=False),
        sa.Column("strategy_version_id", sa.Uuid(), nullable=False),
        sa.Column("judge_id", sa.UUID(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("raw_measurements", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("judge_outputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reasoning", sa.String(), nullable=True),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("failure_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evaluation_logs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("updated_by_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["judge_id"], ["judges.id"], name=op.f("fk_evaluation_results_judge_id_judges")
        ),
        sa.ForeignKeyConstraint(
            ["model_output_id"],
            ["model_outputs.id"],
            name=op.f("fk_evaluation_results_model_output_id_model_outputs"),
        ),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["evaluation_strategy_versions.id"],
            name=op.f("fk_evaluation_results_strategy_version_id_evaluation_strategy_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_results")),
        sa.UniqueConstraint("model_output_id", name=op.f("uq_evaluation_results_model_output_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evaluation_results")
    op.drop_index(op.f("ix_model_outputs_test_case_id"), table_name="model_outputs")
    op.drop_index(op.f("ix_model_outputs_atlas_run_id"), table_name="model_outputs")
    op.drop_table("model_outputs")
    op.drop_table("capability_scores")
    op.drop_table("test_cases")
    op.drop_table("prompts")
    op.drop_table("evaluation_rules")
    op.drop_table("constraints")
    op.drop_table("capability_profiles")
    op.drop_table("artifacts")
    op.drop_table("tasks")
    op.drop_table("report_metrics")
    op.drop_index(op.f("ix_atlas_runs_session_id"), table_name="atlas_runs")
    op.drop_table("atlas_runs")
    op.drop_table("report_versions")
    op.drop_table("benchmark_versions")
    op.drop_table("benchmark_lifecycles")
    op.drop_table("benchmark_category_link")
    op.drop_table("benchmark_capability_link")
    op.drop_index(op.f("ix_reports_project_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("execution_adapter_versions")
    op.drop_table("evaluation_strategy_versions")
    op.drop_index(op.f("ix_evaluation_sessions_project_id"), table_name="evaluation_sessions")
    op.drop_table("evaluation_sessions")
    op.drop_table("dataset_versions")
    op.drop_table("configuration_versions")
    op.drop_index(op.f("ix_benchmarks_project_id"), table_name="benchmarks")
    op.drop_table("benchmarks")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("projects")
    op.drop_table("datasets")
    op.drop_table("organizations")
    op.drop_table("judges")
    op.drop_table("execution_adapters")
    op.drop_table("evaluation_strategies")
    op.drop_table("dataset_sources")
    op.drop_table("dataset_registries")
    op.drop_table("dataset_licenses")
    op.drop_index(op.f("ix_configurations_key"), table_name="configurations")
    op.drop_table("configurations")
    op.drop_table("capabilities")
    op.drop_table("benchmark_categories")
    # ### end Alembic commands ###
