"""Add provider event id

Revision ID: e6888663a7d3
Revises: 9542e8b1087c
Create Date: 2026-08-02 20:11:53.718166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6888663a7d3'
down_revision: Union[str, Sequence[str], None] = '9542e8b1087c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.Enum('BENCHMARK_VERSION', 'CAPABILITY', name='target_type_enum'), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_reason', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leaderboard_snapshots'))
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_organizations_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_organizations_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('outbox_messages',
    sa.Column('outbox_message_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('trace_context', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('outbox_message_id', name=op.f('pk_outbox_messages'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_users_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_users_org_id_organizations')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_users_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_audit_logs_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_audit_logs_updated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('benchmark_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_benchmark_categories_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_benchmark_categories_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_benchmark_categories_name'))
    )
    op.create_table('capabilities',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_capabilities_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_capabilities_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capabilities')),
    sa.UniqueConstraint('name', name=op.f('uq_capabilities_name'))
    )
    op.create_table('credit_accounts',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_credit_accounts_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_credit_accounts_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_credit_accounts_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_accounts')),
    sa.UniqueConstraint('org_id', name=op.f('uq_credit_accounts_org_id'))
    )
    op.create_table('dataset_licenses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_dataset_licenses_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_dataset_licenses_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_licenses'))
    )
    with op.batch_alter_table('dataset_licenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_licenses_name'), ['name'], unique=False)

    op.create_table('dataset_registries',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_dataset_registries_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_dataset_registries_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_registries'))
    )
    with op.batch_alter_table('dataset_registries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_registries_name'), ['name'], unique=False)

    op.create_table('dataset_sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_dataset_sources_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_dataset_sources_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_sources'))
    )
    with op.batch_alter_table('dataset_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_sources_name'), ['name'], unique=False)

    op.create_table('evaluation_strategies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', postgresql.ENUM('EXACT_MATCH', 'LLM_JUDGE', 'SCRIPT', name='strategy_type'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_evaluation_strategies_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_evaluation_strategies_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_strategies')),
    sa.UniqueConstraint('name', name=op.f('uq_evaluation_strategies_name'))
    )
    op.create_table('execution_adapters',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', postgresql.ENUM('LOCAL', 'KUBERNETES', 'AWS_BATCH', name='adapter_type'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_execution_adapters_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_execution_adapters_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_adapters')),
    sa.UniqueConstraint('name', name=op.f('uq_execution_adapters_name'))
    )
    op.create_table('features',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_features_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_features_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_features')),
    sa.UniqueConstraint('name', name=op.f('uq_features_name'))
    )
    op.create_table('invitations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='organization_role'), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', name='invitation_status'), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_invitations_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_invitations_invited_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_invitations_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_invitations_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations'))
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_token'), ['token'], unique=True)

    op.create_table('judges',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('model_identifier', sa.String(length=255), nullable=False),
    sa.Column('prompt_template', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_judges_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_judges_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_judges_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_judges')),
    sa.UniqueConstraint('name', name=op.f('uq_judges_name'))
    )
    with op.batch_alter_table('judges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_judges_organization_id'), ['organization_id'], unique=False)

    op.create_table('leaderboard_snapshot_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('target_model', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['leaderboard_snapshots.id'], name=op.f('fk_leaderboard_snapshot_entries_snapshot_id_leaderboard_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leaderboard_snapshot_entries'))
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_notifications_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_notifications_updated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('organization_members',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='organization_role'), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'PENDING', 'SUSPENDED', 'LEFT', name='membership_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_organization_members_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_members_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_organization_members_updated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_members')),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_org_member')
    )
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_members_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_user_id'), ['user_id'], unique=False)

    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_products_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_products_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_table('usage_records',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_usage_records_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_usage_records_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_usage_records_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_records'))
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_records_org_id'), ['org_id'], unique=False)

    op.create_table('webhook_events',
    sa.Column('provider', sa.Enum('STRIPE', 'RAZORPAY', 'MANUAL', name='payment_provider'), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_webhook_events_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_webhook_events_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events')),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_webhook_event_provider_event_id')
    )
    op.create_table('credit_transactions',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transaction_type', sa.Enum('GRANT', 'PURCHASE', 'DEDUCTION', 'REFUND', name='credit_transaction_type'), nullable=False),
    sa.Column('reference_type', sa.String(length=255), nullable=True),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['credit_accounts.id'], name=op.f('fk_credit_transactions_account_id_credit_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_credit_transactions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_credit_transactions_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_transactions'))
    )
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_reference_id'), ['reference_id'], unique=False)

    op.create_table('evaluation_strategy_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('version_string', sa.String(length=50), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_evaluation_strategy_versions_created_by_id_users')),
    sa.ForeignKeyConstraint(['strategy_id'], ['evaluation_strategies.id'], name=op.f('fk_evaluation_strategy_versions_strategy_id_evaluation_strategies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_strategy_versions')),
    sa.UniqueConstraint('strategy_id', 'version_string', name='uq_strategy_version')
    )
    with op.batch_alter_table('evaluation_strategy_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_strategy_versions_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_strategy_versions_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('execution_adapter_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('adapter_id', sa.UUID(), nullable=False),
    sa.Column('version_string', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['adapter_id'], ['execution_adapters.id'], name=op.f('fk_execution_adapter_versions_adapter_id_execution_adapters')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_execution_adapter_versions_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_adapter_versions')),
    sa.UniqueConstraint('adapter_id', 'version_string', name='uq_adapter_version')
    )
    with op.batch_alter_table('execution_adapter_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_adapter_versions_adapter_id'), ['adapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_adapter_versions_created_by_id'), ['created_by_id'], unique=False)

    op.create_table('prices',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_cycle', sa.Enum('ONE_TIME', 'MONTHLY', 'YEARLY', name='billing_cycle'), nullable=False),
    sa.Column('provider_price_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_prices_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_prices_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_prices_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prices'))
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prices_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prices_provider_price_id'), ['provider_price_id'], unique=False)

    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('created_by_member_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_member_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_projects_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['organization_members.id'], name=op.f('fk_projects_created_by_member_id_organization_members'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_projects_org_id_organizations')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_projects_updated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_member_id'], ['organization_members.id'], name=op.f('fk_projects_updated_by_member_id_organization_members'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('org_id', 'name', name='uq_project_org_name')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=False)

    op.create_table('benchmarks',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_benchmarks_author_id_users')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_benchmarks_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_benchmarks_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_benchmarks_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmarks'))
    )
    with op.batch_alter_table('benchmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benchmarks_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_benchmarks_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_benchmarks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_benchmarks_status'), ['status'], unique=False)

    op.create_table('datasets',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('registry_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('license_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by_member_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'ARCHIVED', name='dataset_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_datasets_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['organization_members.id'], name=op.f('fk_datasets_created_by_member_id_organization_members'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['license_id'], ['dataset_licenses.id'], name=op.f('fk_datasets_license_id_dataset_licenses')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_datasets_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registry_id'], ['dataset_registries.id'], name=op.f('fk_datasets_registry_id_dataset_registries')),
    sa.ForeignKeyConstraint(['source_id'], ['dataset_sources.id'], name=op.f('fk_datasets_source_id_dataset_sources')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_datasets_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets')),
    sa.UniqueConstraint('project_id', 'name', name='uq_dataset_project_name')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_license_id'), ['license_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_registry_id'), ['registry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_source_id'), ['source_id'], unique=False)

    op.create_table('price_features',
    sa.Column('price_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_price_features_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('fk_price_features_feature_id_features'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], name=op.f('fk_price_features_price_id_prices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_price_features_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_features'))
    )
    with op.batch_alter_table('price_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_features_feature_id'), ['feature_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_features_price_id'), ['price_id'], unique=False)

    op.create_table('reports',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_reports_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_reports_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_reports_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_project_id'), ['project_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('price_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELED', 'UNPAID', 'INCOMPLETE', 'TRIALING', name='subscription_status'), nullable=False),
    sa.Column('provider', sa.Enum('STRIPE', 'RAZORPAY', 'MANUAL', name='payment_provider'), nullable=True),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_subscriptions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_subscriptions_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], name=op.f('fk_subscriptions_price_id_prices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_subscriptions_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_price_id'), ['price_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_provider_subscription_id'), ['provider_subscription_id'], unique=False)

    op.create_table('benchmark_capability_link',
    sa.Column('benchmark_id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], name=op.f('fk_benchmark_capability_link_benchmark_id_benchmarks')),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], name=op.f('fk_benchmark_capability_link_capability_id_capabilities')),
    sa.PrimaryKeyConstraint('benchmark_id', 'capability_id', name=op.f('pk_benchmark_capability_link'))
    )
    op.create_table('benchmark_category_link',
    sa.Column('benchmark_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], name=op.f('fk_benchmark_category_link_benchmark_id_benchmarks')),
    sa.ForeignKeyConstraint(['category_id'], ['benchmark_categories.id'], name=op.f('fk_benchmark_category_link_category_id_benchmark_categories')),
    sa.PrimaryKeyConstraint('benchmark_id', 'category_id', name=op.f('pk_benchmark_category_link'))
    )
    op.create_table('benchmark_lifecycles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('benchmark_id', sa.UUID(), nullable=False),
    sa.Column('state', postgresql.ENUM('PROPOSAL', 'DESIGN', 'DRAFT', 'VALIDATION', 'REVIEW', 'PUBLISHED', 'ARCHIVE', name='benchmark_state'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], name=op.f('fk_benchmark_lifecycles_benchmark_id_benchmarks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_benchmark_lifecycles_changed_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_lifecycles'))
    )
    with op.batch_alter_table('benchmark_lifecycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benchmark_lifecycles_changed_by_id'), ['changed_by_id'], unique=False)

    op.create_table('configurations',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('scope', postgresql.ENUM('ENV', 'PROJECT', 'BENCHMARK', name='configuration_scope'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('benchmark_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.CheckConstraint("(scope = 'PROJECT' AND project_id IS NOT NULL AND benchmark_id IS NULL) OR (scope = 'BENCHMARK' AND benchmark_id IS NOT NULL AND project_id IS NULL) OR (scope = 'ENV' AND project_id IS NULL AND benchmark_id IS NULL)", name=op.f('chk_configurations_chk_configuration_scope')),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], name=op.f('fk_configurations_benchmark_id_benchmarks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_configurations_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_configurations_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_configurations_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configurations'))
    )
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configurations_benchmark_id'), ['benchmark_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configurations_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_configurations_project_id'), ['project_id'], unique=False)

    op.create_table('dataset_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('version_string', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('lifecycle', postgresql.ENUM('UPLOADED', 'VALIDATING', 'VALID', 'PUBLISHED', 'FAILED', name='dataset_lifecycle'), nullable=False),
    sa.Column('schema_def', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_dataset_versions_created_by_id_users')),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_dataset_versions_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_versions')),
    sa.UniqueConstraint('dataset_id', 'version_string', name='uq_dataset_version')
    )
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_versions_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_versions_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('invoices',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'PAID', 'VOID', 'UNCOLLECTIBLE', name='invoice_status'), nullable=False),
    sa.Column('provider', sa.Enum('STRIPE', 'RAZORPAY', 'MANUAL', name='payment_provider'), nullable=True),
    sa.Column('provider_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('tax_region', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_invoices_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_invoices_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_invoices_subscription_id_subscriptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_invoices_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_provider_invoice_id'), ['provider_invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('benchmark_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('benchmark_id', sa.UUID(), nullable=False),
    sa.Column('version_string', sa.String(length=50), nullable=False),
    sa.Column('primary_dataset_version_id', sa.Uuid(), nullable=True),
    sa.Column('evaluation_config', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('metric_config', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('scoring_policy', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('evaluation_strategy_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], name=op.f('fk_benchmark_versions_benchmark_id_benchmarks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_benchmark_versions_created_by_id_users')),
    sa.ForeignKeyConstraint(['primary_dataset_version_id'], ['dataset_versions.id'], name=op.f('fk_benchmark_versions_primary_dataset_version_id_dataset_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_versions')),
    sa.UniqueConstraint('benchmark_id', 'version_string', name='uq_benchmark_version')
    )
    with op.batch_alter_table('benchmark_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benchmark_versions_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_benchmark_versions_primary_dataset_version_id'), ['primary_dataset_version_id'], unique=False)

    op.create_table('configuration_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('configuration_id', sa.UUID(), nullable=False),
    sa.Column('version_string', sa.String(length=50), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], name=op.f('fk_configuration_versions_configuration_id_configurations')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_configuration_versions_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration_versions')),
    sa.UniqueConstraint('configuration_id', 'version_string', name='uq_configuration_version')
    )
    with op.batch_alter_table('configuration_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuration_versions_configuration_id'), ['configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configuration_versions_created_by_id'), ['created_by_id'], unique=False)

    op.create_table('payments',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED', 'DISPUTED', name='payment_status'), nullable=False),
    sa.Column('provider', sa.Enum('STRIPE', 'RAZORPAY', 'MANUAL', name='payment_provider'), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=True),
    sa.Column('provider_order_id', sa.String(length=255), nullable=True),
    sa.Column('provider_customer_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_payments_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payments_invoice_id_invoices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_payments_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_payments_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_payments_idempotency_key'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_provider_customer_id'), ['provider_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_provider_order_id'), ['provider_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_provider_payment_id'), ['provider_payment_id'], unique=False)

    op.create_table('benchmark_version_dataset_link',
    sa.Column('benchmark_version_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_version_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_version_id'], ['benchmark_versions.id'], name=op.f('fk_benchmark_version_dataset_link_benchmark_version_id_benchmark_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f('fk_benchmark_version_dataset_link_dataset_version_id_dataset_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('benchmark_version_id', 'dataset_version_id', name=op.f('pk_benchmark_version_dataset_link'))
    )
    op.create_table('executions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('benchmark_version_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_by_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'QUEUED', 'SCHEDULED', 'STARTING', 'RUNNING', 'EVALUATING', 'COMPLETED', 'FAILED', 'RETRYING', 'CANCELLING', 'CANCELLED', 'TIMED_OUT', name='execution_status'), nullable=False),
    sa.Column('target_model', sa.String(length=255), nullable=False),
    sa.Column('execution_config', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('benchmark_hash', sa.String(length=64), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('cancellation_requested', sa.Boolean(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('completed_items', sa.Integer(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_version_id'], ['benchmark_versions.id'], name=op.f('fk_executions_benchmark_version_id_benchmark_versions')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_executions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_executions_project_id_projects')),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['organization_members.id'], name=op.f('fk_executions_submitted_by_id_organization_members')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_executions_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions'))
    )
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_executions_benchmark_version_id'), ['benchmark_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_executions_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_submitted_by_id'), ['submitted_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_target_model'), ['target_model'], unique=False)

    op.create_table('refunds',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED', 'DISPUTED', name='payment_status'), nullable=False),
    sa.Column('provider_refund_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_refunds_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_refunds_payment_id_payments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_refunds_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds'))
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refunds_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_provider_refund_id'), ['provider_refund_id'], unique=False)

    op.create_table('tasks',
    sa.Column('benchmark_version_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_version_id'], ['benchmark_versions.id'], name=op.f('fk_tasks_benchmark_version_id_benchmark_versions')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_tasks_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_tasks_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_benchmark_version_id'), ['benchmark_version_id'], unique=False)

    op.create_table('artifacts',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('LOG', 'LOGS', 'WEIGHTS', 'FILE', 'MODEL_OUTPUT', 'EVALUATION_RESULT', name='artifact_type'), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_artifacts_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_artifacts_execution_id_executions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_artifacts_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_execution_id'), ['execution_id'], unique=False)

    op.create_table('constraints',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_constraints_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_constraints_task_id_tasks')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_constraints_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_constraints'))
    )
    with op.batch_alter_table('constraints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_constraints_task_id'), ['task_id'], unique=False)

    op.create_table('evaluation_rules',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('rule_definition', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_evaluation_rules_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_evaluation_rules_task_id_tasks')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_evaluation_rules_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_rules'))
    )
    with op.batch_alter_table('evaluation_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_rules_task_id'), ['task_id'], unique=False)

    op.create_table('prompts',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('template', sa.String(), nullable=False),
    sa.Column('system_instruction', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_prompts_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_prompts_task_id_tasks')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_prompts_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompts'))
    )
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompts_task_id'), ['task_id'], unique=False)

    op.create_table('report_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('version_string', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_report_versions_created_by_id_users')),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_report_versions_execution_id_executions')),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_report_versions_report_id_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_versions'))
    )
    op.create_table('test_cases',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('expected_output', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_test_cases_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_test_cases_task_id_tasks')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_test_cases_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_cases'))
    )
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_cases_task_id'), ['task_id'], unique=False)

    op.create_table('model_outputs',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('raw_output', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_model_outputs_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_model_outputs_execution_id_executions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], name=op.f('fk_model_outputs_test_case_id_test_cases')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_model_outputs_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_outputs'))
    )
    with op.batch_alter_table('model_outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_outputs_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_outputs_test_case_id'), ['test_case_id'], unique=False)

    op.create_table('report_metrics',
    sa.Column('report_version_id', sa.Uuid(), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_report_metrics_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_version_id'], ['report_versions.id'], name=op.f('fk_report_metrics_report_version_id_report_versions')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_report_metrics_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_metrics'))
    )
    op.create_table('evaluation_results',
    sa.Column('model_output_id', sa.UUID(), nullable=False),
    sa.Column('strategy_version_id', sa.Uuid(), nullable=False),
    sa.Column('judge_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('COMPLETED', 'PARTIAL_SUCCESS', 'FAILED', name='evaluation_status'), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('raw_measurements', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('failure_reasons', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('evaluation_context', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_evaluation_results_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.id'], name=op.f('fk_evaluation_results_judge_id_judges')),
    sa.ForeignKeyConstraint(['model_output_id'], ['model_outputs.id'], name=op.f('fk_evaluation_results_model_output_id_model_outputs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['evaluation_strategy_versions.id'], name=op.f('fk_evaluation_results_strategy_version_id_evaluation_strategy_versions')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_evaluation_results_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_results')),
    sa.UniqueConstraint('model_output_id', name=op.f('uq_evaluation_results_model_output_id'))
    )
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_results_judge_id'), ['judge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_results_strategy_version_id'), ['strategy_version_id'], unique=False)

    op.create_table('capability_profiles',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('strategy_version_id', sa.Uuid(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('score_explanation', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('profile_metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_capability_profiles_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluation_results.id'], name=op.f('fk_capability_profiles_evaluation_id_evaluation_results'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_capability_profiles_execution_id_executions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['evaluation_strategy_versions.id'], name=op.f('fk_capability_profiles_strategy_version_id_evaluation_strategy_versions')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_capability_profiles_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability_profiles'))
    )
    with op.batch_alter_table('capability_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capability_profiles_evaluation_id'), ['evaluation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capability_profiles_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capability_profiles_strategy_version_id'), ['strategy_version_id'], unique=False)

    op.create_table('evaluation_artifacts',
    sa.Column('evaluation_result_id', sa.UUID(), nullable=False),
    sa.Column('artifact_uri', sa.String(length=1024), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_evaluation_artifacts_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evaluation_result_id'], ['evaluation_results.id'], name=op.f('fk_evaluation_artifacts_evaluation_result_id_evaluation_results'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_evaluation_artifacts_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_artifacts'))
    )
    with op.batch_alter_table('evaluation_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_artifacts_evaluation_result_id'), ['evaluation_result_id'], unique=False)

    op.create_table('evaluation_result_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_result_id', sa.UUID(), nullable=False),
    sa.Column('judge_outputs', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('evaluation_logs', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_result_id'], ['evaluation_results.id'], name=op.f('fk_evaluation_result_details_evaluation_result_id_evaluation_results'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_result_details')),
    sa.UniqueConstraint('evaluation_result_id', name=op.f('uq_evaluation_result_details_evaluation_result_id'))
    )
    op.create_table('capability_scores',
    sa.Column('capability_profile_id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], name=op.f('fk_capability_scores_capability_id_capabilities')),
    sa.ForeignKeyConstraint(['capability_profile_id'], ['capability_profiles.id'], name=op.f('fk_capability_scores_capability_profile_id_capability_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_capability_scores_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_capability_scores_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability_scores'))
    )
    with op.batch_alter_table('capability_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capability_scores_capability_id'), ['capability_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capability_scores_capability_profile_id'), ['capability_profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capability_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capability_scores_capability_profile_id'))
        batch_op.drop_index(batch_op.f('ix_capability_scores_capability_id'))

    op.drop_table('capability_scores')
    op.drop_table('evaluation_result_details')
    with op.batch_alter_table('evaluation_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_artifacts_evaluation_result_id'))

    op.drop_table('evaluation_artifacts')
    with op.batch_alter_table('capability_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capability_profiles_strategy_version_id'))
        batch_op.drop_index(batch_op.f('ix_capability_profiles_execution_id'))
        batch_op.drop_index(batch_op.f('ix_capability_profiles_evaluation_id'))

    op.drop_table('capability_profiles')
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_results_strategy_version_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_results_judge_id'))

    op.drop_table('evaluation_results')
    op.drop_table('report_metrics')
    with op.batch_alter_table('model_outputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_outputs_test_case_id'))
        batch_op.drop_index(batch_op.f('ix_model_outputs_execution_id'))

    op.drop_table('model_outputs')
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_cases_task_id'))

    op.drop_table('test_cases')
    op.drop_table('report_versions')
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompts_task_id'))

    op.drop_table('prompts')
    with op.batch_alter_table('evaluation_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_rules_task_id'))

    op.drop_table('evaluation_rules')
    with op.batch_alter_table('constraints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_constraints_task_id'))

    op.drop_table('constraints')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_execution_id'))

    op.drop_table('artifacts')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_benchmark_version_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refunds_provider_refund_id'))
        batch_op.drop_index(batch_op.f('ix_refunds_payment_id'))

    op.drop_table('refunds')
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_executions_target_model'))
        batch_op.drop_index(batch_op.f('ix_executions_submitted_by_id'))
        batch_op.drop_index('ix_executions_status_created_at')
        batch_op.drop_index(batch_op.f('ix_executions_project_id'))
        batch_op.drop_index(batch_op.f('ix_executions_benchmark_version_id'))

    op.drop_table('executions')
    op.drop_table('benchmark_version_dataset_link')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_provider_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payments_provider_order_id'))
        batch_op.drop_index(batch_op.f('ix_payments_provider_customer_id'))
        batch_op.drop_index(batch_op.f('ix_payments_org_id'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))

    op.drop_table('payments')
    with op.batch_alter_table('configuration_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuration_versions_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_configuration_versions_configuration_id'))

    op.drop_table('configuration_versions')
    with op.batch_alter_table('benchmark_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benchmark_versions_primary_dataset_version_id'))
        batch_op.drop_index(batch_op.f('ix_benchmark_versions_created_by_id'))

    op.drop_table('benchmark_versions')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_provider_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_org_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_versions_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_versions_created_by_id'))

    op.drop_table('dataset_versions')
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configurations_project_id'))
        batch_op.drop_index(batch_op.f('ix_configurations_key'))
        batch_op.drop_index(batch_op.f('ix_configurations_benchmark_id'))

    op.drop_table('configurations')
    with op.batch_alter_table('benchmark_lifecycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benchmark_lifecycles_changed_by_id'))

    op.drop_table('benchmark_lifecycles')
    op.drop_table('benchmark_category_link')
    op.drop_table('benchmark_capability_link')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_provider_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_price_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_org_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_project_id'))

    op.drop_table('reports')
    with op.batch_alter_table('price_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_features_price_id'))
        batch_op.drop_index(batch_op.f('ix_price_features_feature_id'))

    op.drop_table('price_features')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_source_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_registry_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_project_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_name'))
        batch_op.drop_index(batch_op.f('ix_datasets_license_id'))

    op.drop_table('datasets')
    with op.batch_alter_table('benchmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benchmarks_status'))
        batch_op.drop_index(batch_op.f('ix_benchmarks_project_id'))
        batch_op.drop_index(batch_op.f('ix_benchmarks_name'))
        batch_op.drop_index(batch_op.f('ix_benchmarks_author_id'))

    op.drop_table('benchmarks')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_slug'))

    op.drop_table('projects')
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prices_provider_price_id'))
        batch_op.drop_index(batch_op.f('ix_prices_product_id'))

    op.drop_table('prices')
    with op.batch_alter_table('execution_adapter_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_adapter_versions_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_execution_adapter_versions_adapter_id'))

    op.drop_table('execution_adapter_versions')
    with op.batch_alter_table('evaluation_strategy_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_strategy_versions_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_strategy_versions_created_by_id'))

    op.drop_table('evaluation_strategy_versions')
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_transactions_reference_id'))
        batch_op.drop_index(batch_op.f('ix_credit_transactions_account_id'))

    op.drop_table('credit_transactions')
    op.drop_table('webhook_events')
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_records_org_id'))

    op.drop_table('usage_records')
    op.drop_table('products')
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_organization_members_organization_id'))

    op.drop_table('organization_members')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    op.drop_table('leaderboard_snapshot_entries')
    with op.batch_alter_table('judges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_judges_organization_id'))

    op.drop_table('judges')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token'))
        batch_op.drop_index(batch_op.f('ix_invitations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_invitations_email'))

    op.drop_table('invitations')
    op.drop_table('features')
    op.drop_table('execution_adapters')
    op.drop_table('evaluation_strategies')
    with op.batch_alter_table('dataset_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_sources_name'))

    op.drop_table('dataset_sources')
    with op.batch_alter_table('dataset_registries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_registries_name'))

    op.drop_table('dataset_registries')
    with op.batch_alter_table('dataset_licenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_licenses_name'))

    op.drop_table('dataset_licenses')
    op.drop_table('credit_accounts')
    op.drop_table('capabilities')
    op.drop_table('benchmark_categories')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index('ix_audit_logs_entity')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('outbox_messages')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    op.drop_table('leaderboard_snapshots')
    # ### end Alembic commands ###
