/**
 * Domain — Models Mock Data
 * 50 models across 12 providers for the Atlas Model Registry.
 */

import type { RegistryModel } from './types';

/* ----------------------------------------------------------------------- */
/*  Helpers                                                                  */
/* ----------------------------------------------------------------------- */

function trend(base: number, length = 12, variance = 3): { date: string; accuracy: number; latencyMs: number; costUsd: number; hallucinationRate: number; benchmarkScore: number }[] {
  return Array.from({ length }, (_, i) => {
    const d = new Date('2026-07-01');
    d.setDate(d.getDate() - (length - i) * 7);
    return {
      date: d.toISOString().slice(0, 10),
      accuracy: Math.min(99, base + i * 0.3 + (Math.random() - 0.5) * variance),
      latencyMs: 800 + Math.random() * 600,
      costUsd: 0.002 + Math.random() * 0.004,
      hallucinationRate: Math.max(1, 8 - i * 0.3 + (Math.random() - 0.5) * 2),
      benchmarkScore: Math.min(99, base - 2 + i * 0.4 + (Math.random() - 0.5) * variance),
    };
  });
}

function caps(domains: number[]) {
  const labels = ['Coding', 'Reasoning', 'Math', 'Knowledge', 'Vision', 'Safety', 'Tool Use', 'Speed'];
  return labels.map((d, i) => ({ domain: d, score: domains[i] ?? 70, label: d }));
}

/* ----------------------------------------------------------------------- */
/*  Mock Models                                                              */
/* ----------------------------------------------------------------------- */

export const MOCK_MODELS: RegistryModel[] = [
  // ── OpenAI ──────────────────────────────────────────────────────────────
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    family: 'GPT-4',
    version: '2024-11-20',
    description: 'Multimodal flagship — text, vision, and audio with low latency.',
    architecture: 'Transformer MoE',
    tokenizer: 'cl100k_base',
    parameterCount: '~200B (est.)',
    contextWindow: 128000,
    modalities: ['text', 'vision', 'audio', 'code'],
    capabilityTags: ['Chat', 'Vision', 'Audio', 'Tool Calling', 'Function Calling', 'Code', 'Long Context', 'Streaming'],
    status: 'active',
    license: 'Proprietary',
    releaseDate: '2024-05-13',
    registeredAt: '2024-05-14T09:00:00Z',
    lastEvaluated: '2026-07-18T12:00:00Z',
    overallScore: 91.2,
    latencyMs: 820,
    evaluationCount: 47,
    profile: { modelId: 'gpt-4o', profileVersion: '1.3', taxonomyVersion: '1.0', capabilities: caps([91, 87, 84, 83, 88, 95, 89, 82]) },
    health: { availability: 99.9, reliability: 99.7, errorRate: 0.3, responseQuality: 94, status: 'healthy', lastChecked: '2026-07-22T08:00:00Z' },
    cost: { inputPer1kTokens: 0.005, outputPer1kTokens: 0.015, averageCostPerCall: 0.012, monthlyEstimate: 340, projectedMonthly: 380, currency: 'USD' },
    deployment: { status: 'deployed', endpoint: 'https://api.openai.com/v1', region: 'us-east-1', runtime: 'OpenAI API', provider: 'OpenAI' },
    versions: [
      { version: '2024-11-20', name: 'GPT-4o (Nov 2024)', releaseDate: '2024-11-20', changes: 'Improved instruction following', isLatest: true, isCurrent: true },
      { version: '2024-08-06', name: 'GPT-4o (Aug 2024)', releaseDate: '2024-08-06', changes: 'Structured outputs, improved vision' },
      { version: '2024-05-13', name: 'GPT-4o (Launch)', releaseDate: '2024-05-13', changes: 'Initial release with native audio/vision' },
    ],
    benchmarkScores: [
      { benchmarkId: 'mmlu', benchmarkName: 'MMLU', category: 'knowledge', score: 88.7, percentile: 92, evaluatedAt: '2026-07-18', runId: 'run-001' },
      { benchmarkId: 'humaneval', benchmarkName: 'HumanEval', category: 'coding', score: 90.2, percentile: 88, evaluatedAt: '2026-07-18', runId: 'run-002' },
      { benchmarkId: 'gsm8k', benchmarkName: 'GSM8K', category: 'mathematics', score: 95.3, percentile: 95, evaluatedAt: '2026-07-18', runId: 'run-003' },
      { benchmarkId: 'arc', benchmarkName: 'ARC-Challenge', category: 'reasoning', score: 87.4, percentile: 89, evaluatedAt: '2026-07-18', runId: 'run-004' },
      { benchmarkId: 'hellaswag', benchmarkName: 'HellaSwag', category: 'language', score: 93.1, percentile: 91, evaluatedAt: '2026-07-18', runId: 'run-005' },
    ],
    evaluationHistory: [
      { id: 'eh-001', benchmarkName: 'MMLU', score: 88.7, status: 'completed', runAt: '2026-07-18', duration: '12m' },
      { id: 'eh-002', benchmarkName: 'HumanEval', score: 90.2, status: 'completed', runAt: '2026-07-17', duration: '4m' },
    ],
    performanceTrend: trend(86, 12, 2),
    intelligenceCard: {
      strengths: ['Excellent multimodal reasoning', 'Strong coding & tool use', 'Low hallucination rate'],
      weaknesses: ['Higher cost vs open models', 'No fine-tuning access', 'Rate limits on burst traffic'],
      bestUseCases: ['Code generation', 'Vision analysis', 'Agent workflows', 'Complex reasoning'],
      avoidFor: ['Budget-sensitive high-volume inference', 'Edge deployment'],
    },
    defaultTemperature: 1.0, defaultTopP: 1.0, defaultMaxTokens: 4096,
  },

  {
    id: 'gpt-4.1',
    name: 'GPT-4.1',
    provider: 'OpenAI',
    family: 'GPT-4',
    version: '2025-04-14',
    description: 'Improved frontier model with stronger coding and long-context performance.',
    architecture: 'Transformer',
    tokenizer: 'o200k_base',
    parameterCount: '~200B (est.)',
    contextWindow: 1000000,
    modalities: ['text', 'vision', 'code'],
    capabilityTags: ['Chat', 'Vision', 'Tool Calling', 'Code', 'Long Context', 'Streaming', 'Function Calling'],
    status: 'active',
    license: 'Proprietary',
    releaseDate: '2025-04-14',
    registeredAt: '2025-04-15T09:00:00Z',
    lastEvaluated: '2026-07-19T10:00:00Z',
    overallScore: 93.4,
    latencyMs: 740,
    evaluationCount: 32,
    profile: { modelId: 'gpt-4.1', profileVersion: '1.0', taxonomyVersion: '1.0', capabilities: caps([94, 90, 88, 87, 86, 96, 91, 84]) },
    health: { availability: 99.8, reliability: 99.6, errorRate: 0.4, responseQuality: 95, status: 'healthy', lastChecked: '2026-07-22T08:00:00Z' },
    cost: { inputPer1kTokens: 0.002, outputPer1kTokens: 0.008, averageCostPerCall: 0.006, monthlyEstimate: 210, projectedMonthly: 240, currency: 'USD' },
    deployment: { status: 'deployed', endpoint: 'https://api.openai.com/v1', region: 'us-east-1', runtime: 'OpenAI API', provider: 'OpenAI' },
    versions: [
      { version: '2025-04-14', name: 'GPT-4.1', releaseDate: '2025-04-14', changes: 'Initial release', isLatest: true, isCurrent: true },
    ],
    benchmarkScores: [
      { benchmarkId: 'mmlu', benchmarkName: 'MMLU', category: 'knowledge', score: 91.2, percentile: 96, evaluatedAt: '2026-07-19', runId: 'run-010' },
      { benchmarkId: 'humaneval', benchmarkName: 'HumanEval', category: 'coding', score: 93.5, percentile: 95, evaluatedAt: '2026-07-19', runId: 'run-011' },
      { benchmarkId: 'gsm8k', benchmarkName: 'GSM8K', category: 'mathematics', score: 96.8, percentile: 97, evaluatedAt: '2026-07-19', runId: 'run-012' },
    ],
    evaluationHistory: [
      { id: 'eh-010', benchmarkName: 'MMLU', score: 91.2, status: 'completed', runAt: '2026-07-19', duration: '11m' },
    ],
    performanceTrend: trend(89, 12, 2),
    intelligenceCard: {
      strengths: ['Best-in-class coding', '1M context window', 'Improved instruction following'],
      weaknesses: ['Proprietary — no weights access', 'Cost premium vs GPT-4o Mini'],
      bestUseCases: ['Long document analysis', 'Large codebase tasks', 'Complex agent chains'],
      avoidFor: ['Simple Q&A where GPT-4o Mini suffices', 'Audio/video tasks'],
    },
    defaultTemperature: 1.0, defaultTopP: 1.0, defaultMaxTokens: 8192,
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'OpenAI',
    family: 'GPT-4',
    version: '2024-07-18',
    description: 'Cost-efficient small model with strong reasoning and vision.',
    architecture: 'Transformer',
    tokenizer: 'o200k_base',
    parameterCount: '~8B (est.)',
    contextWindow: 128000,
    modalities: ['text', 'vision', 'code'],
    capabilityTags: ['Chat', 'Vision', 'Tool Calling', 'Code', 'Streaming'],
    status: 'active',
    license: 'Proprietary',
    releaseDate: '2024-07-18',
    registeredAt: '2024-07-19T09:00:00Z',
    lastEvaluated: '2026-07-15T10:00:00Z',
    overallScore: 79.3,
    latencyMs: 340,
    evaluationCount: 28,
    profile: { modelId: 'gpt-4o-mini', profileVersion: '1.0', taxonomyVersion: '1.0', capabilities: caps([78, 75, 72, 74, 70, 88, 76, 92]) },
    health: { availability: 99.95, reliability: 99.8, errorRate: 0.2, responseQuality: 85, status: 'healthy', lastChecked: '2026-07-22T08:00:00Z' },
    cost: { inputPer1kTokens: 0.00015, outputPer1kTokens: 0.0006, averageCostPerCall: 0.0004, monthlyEstimate: 18, projectedMonthly: 22, currency: 'USD' },
    deployment: { status: 'deployed', endpoint: 'https://api.openai.com/v1', region: 'global', runtime: 'OpenAI API', provider: 'OpenAI' },
    versions: [
      { version: '2024-07-18', name: 'GPT-4o Mini', releaseDate: '2024-07-18', changes: 'Initial release', isLatest: true, isCurrent: true },
    ],
    benchmarkScores: [
      { benchmarkId: 'mmlu', benchmarkName: 'MMLU', category: 'knowledge', score: 82.0, percentile: 72, evaluatedAt: '2026-07-15', runId: 'run-020' },
      { benchmarkId: 'humaneval', benchmarkName: 'HumanEval', category: 'coding', score: 87.2, percentile: 75, evaluatedAt: '2026-07-15', runId: 'run-021' },
    ],
    evaluationHistory: [
      { id: 'eh-020', benchmarkName: 'MMLU', score: 82.0, status: 'completed', runAt: '2026-07-15', duration: '9m' },
    ],
    performanceTrend: trend(76, 12, 3),
    intelligenceCard: {
      strengths: ['Very low cost', 'Low latency', 'Good for high-volume tasks'],
      weaknesses: ['Weaker on complex multi-step reasoning', 'Smaller context than GPT-4.1'],
      bestUseCases: ['Classification', 'Summarization', 'Simple Q&A', 'High-volume pipelines'],
      avoidFor: ['Complex reasoning chains', 'Long document analysis'],
    },
    defaultTemperature: 1.0, defaultTopP: 1.0, defaultMaxTokens: 4096,
  },

  // ── Anthropic ────────────────────────────────────────────────────────────
  {
    id: 'claude-4-sonnet',
    name: 'Claude 4 Sonnet',
    provider: 'Anthropic',
    family: 'Claude 4',
    version: '20250514',
    description: 'Best-in-class coding and reasoning with strong safety alignment.',
    architecture: 'Transformer',
    tokenizer: 'Custom BPE',
    parameterCount: '~200B (est.)',
    contextWindow: 200000,
    modalities: ['text', 'vision', 'code'],
    capabilityTags: ['Chat', 'Vision', 'Tool Calling', 'Code', 'Long Context', 'Streaming', 'Agents', 'Function Calling'],
    status: 'active',
    license: 'Proprietary',
    releaseDate: '2025-05-14',
    registeredAt: '2025-05-15T09:00:00Z',
    lastEvaluated: '2026-07-20T10:00:00Z',
    overallScore: 93.8,
    latencyMs: 910,
    evaluationCount: 38,
    profile: { modelId: 'claude-4-sonnet', profileVersion: '1.3', taxonomyVersion: '1.0', capabilities: caps([94, 90, 82, 86, 84, 98, 86, 78]) },
    health: { availability: 99.7, reliability: 99.5, errorRate: 0.5, responseQuality: 96, status: 'healthy', lastChecked: '2026-07-22T08:00:00Z' },
    cost: { inputPer1kTokens: 0.003, outputPer1kTokens: 0.015, averageCostPerCall: 0.011, monthlyEstimate: 290, projectedMonthly: 320, currency: 'USD' },
    deployment: { status: 'deployed', endpoint: 'https://api.anthropic.com/v1', region: 'us-east-1', runtime: 'Anthropic API', provider: 'Anthropic' },
    versions: [
      { version: '20250514', name: 'Claude 4 Sonnet', releaseDate: '2025-05-14', changes: 'Initial release', isLatest: true, isCurrent: true },
    ],
    benchmarkScores: [
      { benchmarkId: 'mmlu', benchmarkName: 'MMLU', category: 'knowledge', score: 90.8, percentile: 95, evaluatedAt: '2026-07-20', runId: 'run-030' },
      { benchmarkId: 'humaneval', benchmarkName: 'HumanEval', category: 'coding', score: 93.7, percentile: 96, evaluatedAt: '2026-07-20', runId: 'run-031' },
      { benchmarkId: 'gsm8k', benchmarkName: 'GSM8K', category: 'mathematics', score: 91.2, percentile: 93, evaluatedAt: '2026-07-20', runId: 'run-032' },
    ],
    evaluationHistory: [
      { id: 'eh-030', benchmarkName: 'MMLU', score: 90.8, status: 'completed', runAt: '2026-07-20', duration: '13m' },
      { id: 'eh-031', benchmarkName: 'HumanEval', score: 93.7, status: 'completed', runAt: '2026-07-19', duration: '5m' },
    ],
    performanceTrend: trend(89, 12, 2),
    intelligenceCard: {
      strengths: ['Best-in-class coding', 'Strong safety alignment', 'Extended thinking mode', 'Excellent instruction following'],
      weaknesses: ['Higher output token cost', 'Slower on very long outputs'],
      bestUseCases: ['Code generation & review', 'Agent workflows', 'Legal/research documents', 'Safety-sensitive applications'],
      avoidFor: ['Budget-conscious batch jobs', 'Real-time voice interfaces'],
    },
    defaultTemperature: 1.0, defaultTopP: 1.0, defaultMaxTokens: 8096,
  },
  {
    id: 'claude-4-haiku',
    name: 'Claude 4 Haiku',
    provider: 'Anthropic',
    family: 'Claude 4',
    version: '20250514',
    description: 'Fastest and most compact Claude model for near-instant responses.',
    architecture: 'Transformer',
    tokenizer: 'Custom BPE',
    parameterCount: '~20B (est.)',
    contextWindow: 200000,
    modalities: ['text', 'vision', 'code'],
    capabilityTags: ['Chat', 'Vision', 'Tool Calling', 'Code', 'Streaming'],
    status: 'active',
    license: 'Proprietary',
    releaseDate: '2025-05-14',
    registeredAt: '2025-05-15T09:00:00Z',
    lastEvaluated: '2026-07-18T10:00:00Z',
    overallScore: 78.1,
    latencyMs: 280,
    evaluationCount: 21,
    profile: { modelId: 'claude-4-haiku', profileVersion: '1.0', taxonomyVersion: '1.0', capabilities: caps([76, 74, 68, 72, 65, 90, 71, 96]) },
    health: { availability: 99.9, reliability: 99.8, errorRate: 0.2, responseQuality: 84, status: 'healthy', lastChecked: '2026-07-22T08:00:00Z' },
    cost: { inputPer1kTokens: 0.00025, outputPer1kTokens: 0.00125, averageCostPerCall: 0.0008, monthlyEstimate: 32, projectedMonthly: 36, currency: 'USD' },
    deployment: { status: 'deployed', endpoint: 'https://api.anthropic.com/v1', region: 'global', runtime: 'Anthropic API', provider: 'Anthropic' },
    versions: [{ version: '20250514', name: 'Claude 4 Haiku', releaseDate: '2025-05-14', changes: 'Initial release', isLatest: true, isCurrent: true }],
    benchmarkScores: [
      { benchmarkId: 'mmlu', benchmarkName: 'MMLU', category: 'knowledge', score: 79.4, percentile: 70, evaluatedAt: '2026-07-18', runId: 'run-040' },
    ],
    evaluationHistory: [{ id: 'eh-040', benchmarkName: 'MMLU', score: 79.4, status: 'completed', runAt: '2026-07-18', duration: '8m' }],
    performanceTrend: trend(74, 12, 3),
    intelligenceCard: {
      strengths: ['Extremely fast', 'Low cost', 'Good safety profile'],
      weaknesses: ['Less capable on complex tasks', 'Weaker math'],
      bestUseCases: ['Chatbots', 'Summarization', 'Fast extraction'],
      avoidFor: ['Complex reasoning', 'Long document analysis'],
    },
    defaultTemperature: 1.0, defaultTopP: 1.0, defaultMaxTokens: 4096,
  },

  // ── Google ───────────────────────────────────────────────────────────────
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'Google',
    family: 'Gemini',
    version: '2025-06',
    description: 'Long-context reasoning powerhouse with native multimodal understanding.',
    architecture: 'Transformer MoE',
    tokenizer: 'SentencePiece',
    parameterCount: '~1.5T MoE',
    contextWindow: 1000000,
    modalities: ['text', 'vision', 'audio', 'video', 'code'],
    capabilityTags: ['Chat', 'Vision', 'Audio', 'Tool Calling', 'Code', 'Long Context', 'Streaming', 'Multimodal'],
    status: 'active',
    license: 'Proprietary',
    releaseDate: '2025-06-01',
    registeredAt: '2025-06-02T09:00:00Z',
    lastEvaluated: '2026-07-20T12:00:00Z',
    overallScore: 92.6,
    latencyMs: 1100,
    evaluationCount: 35,
    profile: { modelId: 'gemini-2.5-pro', profileVersion: '1.2', taxonomyVersion: '1.0', capabilities: caps([90, 92, 91, 83, 90, 93, 85, 72]) },
    health: { availability: 99.5, reliability: 99.2, errorRate: 0.8, responseQuality: 93, status: 'healthy', lastChecked: '2026-07-22T08:00:00Z' },
    cost: { inputPer1kTokens: 0.00125, outputPer1kTokens: 0.005, averageCostPerCall: 0.008, monthlyEstimate: 260, projectedMonthly: 290, currency: 'USD' },
    deployment: { status: 'deployed', endpoint: 'https://generativelanguage.googleapis.com', region: 'global', runtime: 'Vertex AI', provider: 'Google' },
    versions: [{ version: '2025-06', name: 'Gemini 2.5 Pro', releaseDate: '2025-06-01', changes: 'Initial release with 1M context', isLatest: true, isCurrent: true }],
    benchmarkScores: [
      { benchmarkId: 'mmlu', benchmarkName: 'MMLU', category: 'knowledge', score: 90.1, percentile: 94, evaluatedAt: '2026-07-20', runId: 'run-050' },
      { benchmarkId: 'gsm8k', benchmarkName: 'GSM8K', category: 'mathematics', score: 97.1, percentile: 98, evaluatedAt: '2026-07-20', runId: 'run-051' },
    ],
    evaluationHistory: [{ id: 'eh-050', benchmarkName: 'MMLU', score: 90.1, status: 'completed', runAt: '2026-07-20', duration: '14m' }],
    performanceTrend: trend(88, 12, 2),
    intelligenceCard: {
      strengths: ['Best math performance', '1M context window', 'Native video understanding'],
      weaknesses: ['Higher latency on large contexts', 'Slower streaming'],
      bestUseCases: ['Long video analysis', 'Scientific reasoning', 'Large codebase comprehension'],
      avoidFor: ['Low-latency applications', 'Simple chat'],
    },
    defaultTemperature: 1.0, defaultTopP: 0.95, defaultMaxTokens: 8192,
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'Google',
    family: 'Gemini',
    version: '2025-05',
    description: 'Fast, efficient Gemini with adaptive thinking for cost-performance balance.',
    architecture: 'Transformer',
    tokenizer: 'SentencePiece',
    parameterCount: '~30B (est.)',
    contextWindow: 1000000,
    modalities: ['text', 'vision', 'audio', 'code'],
    capabilityTags: ['Chat', 'Vision', 'Tool Calling', 'Code', 'Long Context', 'Streaming'],
    status: 'active',
    license: 'Proprietary',
    releaseDate: '2025-05-01',
    registeredAt: '2025-05-02T09:00:00Z',
    lastEvaluated: '2026-07-18T12:00:00Z',
    overallScore: 84.2,
    latencyMs: 420,
    evaluationCount: 29,
    profile: { modelId: 'gemini-2.5-flash', profileVersion: '1.0', taxonomyVersion: '1.0', capabilities: caps([82, 84, 83, 78, 80, 88, 79, 88]) },
    health: { availability: 99.8, reliability: 99.5, errorRate: 0.5, responseQuality: 88, status: 'healthy', lastChecked: '2026-07-22T08:00:00Z' },
    cost: { inputPer1kTokens: 0.000075, outputPer1kTokens: 0.0003, averageCostPerCall: 0.0002, monthlyEstimate: 24, projectedMonthly: 28, currency: 'USD' },
    deployment: { status: 'deployed', endpoint: 'https://generativelanguage.googleapis.com', region: 'global', runtime: 'Vertex AI', provider: 'Google' },
    versions: [{ version: '2025-05', name: 'Gemini 2.5 Flash', releaseDate: '2025-05-01', changes: 'Initial release', isLatest: true, isCurrent: true }],
    benchmarkScores: [
      { benchmarkId: 'mmlu', benchmarkName: 'MMLU', category: 'knowledge', score: 85.3, percentile: 80, evaluatedAt: '2026-07-18', runId: 'run-060' },
    ],
    evaluationHistory: [{ id: 'eh-060', benchmarkName: 'MMLU', score: 85.3, status: 'completed', runAt: '2026-07-18', duration: '9m' }],
    performanceTrend: trend(80, 12, 3),
    intelligenceCard: {
      strengths: ['Very low cost', 'Fast response', 'Long context at low price'],
      weaknesses: ['Less capable than Pro on hard tasks'],
      bestUseCases: ['High-volume pipelines', 'Long document summarization', 'Real-time chat'],
      avoidFor: ['Complex scientific reasoning', 'Expert-level code generation'],
    },
    defaultTemperature: 1.0, defaultTopP: 0.95, defaultMaxTokens: 8192,
  },

  // ── Meta ────────────────────────────────────────────────────────────────
  {
    id: 'llama-4-maverick',
    name: 'LLaMA 4 Maverick',
    provider: 'Meta',
    family: 'LLaMA 4',
    version: '2025-04',
    description: 'Open-weight MoE frontier model — strong general performance with permissive license.',
    architecture: 'MoE Transformer',
    tokenizer: 'tiktoken-like',
    parameterCount: '400B MoE (17B active)',
    contextWindow: 1000000,
    modalities: ['text', 'vision', 'code'],
    capabilityTags: ['Chat', 'Vision', 'Tool Calling', 'Code', 'Long Context', 'Streaming', 'Fine-tunable'],
    status: 'active',
    license: 'Llama',
    releaseDate: '2025-04-05',
    registeredAt: '2025-04-06T09:00:00Z',
    lastEvaluated: '2026-07-19T10:00:00Z',
    overallScore: 86.3,
    latencyMs: 680,
    evaluationCount: 26,
    profile: { modelId: 'llama-4-maverick', profileVersion: '1.1', taxonomyVersion: '1.0', capabilities: caps([84, 82, 79, 75, 78, 86, 79, 80]) },
    health: { availability: 98.5, reliability: 98.2, errorRate: 1.8, responseQuality: 87, status: 'healthy', lastChecked: '2026-07-22T08:00:00Z' },
    cost: { inputPer1kTokens: 0.0002, outputPer1kTokens: 0.0006, averageCostPerCall: 0.0004, monthlyEstimate: 45, projectedMonthly: 52, currency: 'USD' },
    deployment: { status: 'deployed', endpoint: 'self-hosted', region: 'us-west-2', runtime: 'vLLM', gpu: 'H100 x8', provider: 'Self-hosted' },
    versions: [
      { version: '2025-04', name: 'LLaMA 4 Maverick', releaseDate: '2025-04-05', changes: 'Initial release', isLatest: true, isCurrent: true },
    ],
    benchmarkScores: [
      { benchmarkId: 'mmlu', benchmarkName: 'MMLU', category: 'knowledge', score: 85.5, percentile: 82, evaluatedAt: '2026-07-19', runId: 'run-070' },
      { benchmarkId: 'humaneval', benchmarkName: 'HumanEval', category: 'coding', score: 87.4, percentile: 79, evaluatedAt: '2026-07-19', runId: 'run-071' },
    ],
    evaluationHistory: [{ id: 'eh-070', benchmarkName: 'MMLU', score: 85.5, status: 'completed', runAt: '2026-07-19', duration: '11m' }],
    performanceTrend: trend(81, 12, 3),
    intelligenceCard: {
      strengths: ['Open weights — full control', 'Fine-tunable', 'Competitive with proprietary models', 'Very long context'],
      weaknesses: ['Self-hosting infrastructure required', 'Higher operational overhead'],
      bestUseCases: ['Custom fine-tuning', 'Private deployment', 'Research', 'Cost-sensitive at scale'],
      avoidFor: ['Managed API simplicity', 'Teams without ML infra'],
    },
    defaultTemperature: 0.6, defaultTopP: 0.9, defaultMaxTokens: 4096,
  },
  {
    id: 'llama-4-scout',
    name: 'LLaMA 4 Scout',
    provider: 'Meta',
    family: 'LLaMA 4',
    version: '2025-04',
    description: 'Efficient 17B active parameter model optimised for speed and cost.',
    architecture: 'MoE Transformer',
    tokenizer: 'tiktoken-like',
    parameterCount: '109B MoE (17B active)',
    contextWindow: 10000000,
    modalities: ['text', 'vision', 'code'],
    capabilityTags: ['Chat', 'Vision', 'Code', 'Streaming', 'Fine-tunable', 'Long Context'],
    status: 'active',
    license: 'Llama',
    releaseDate: '2025-04-05',
    registeredAt: '2025-04-06T09:00:00Z',
    lastEvaluated: '2026-07-16T10:00:00Z',
    overallScore: 79.8,
    latencyMs: 420,
    evaluationCount: 18,
    profile: { modelId: 'llama-4-scout', profileVersion: '1.0', taxonomyVersion: '1.0', capabilities: caps([78, 77, 73, 70, 72, 82, 72, 88]) },
    health: { availability: 98.2, reliability: 97.9, errorRate: 2.1, responseQuality: 83, status: 'healthy', lastChecked: '2026-07-22T08:00:00Z' },
    cost: { inputPer1kTokens: 0.00008, outputPer1kTokens: 0.00024, averageCostPerCall: 0.00014, monthlyEstimate: 18, projectedMonthly: 22, currency: 'USD' },
    deployment: { status: 'deployed', endpoint: 'self-hosted', region: 'us-west-2', runtime: 'vLLM', gpu: 'H100 x4', provider: 'Self-hosted' },
    versions: [{ version: '2025-04', name: 'LLaMA 4 Scout', releaseDate: '2025-04-05', changes: 'Initial release', isLatest: true, isCurrent: true }],
    benchmarkScores: [
      { benchmarkId: 'mmlu', benchmarkName: 'MMLU', category: 'knowledge', score: 79.9, percentile: 71, evaluatedAt: '2026-07-16', runId: 'run-080' },
    ],
    evaluationHistory: [{ id: 'eh-080', benchmarkName: 'MMLU', score: 79.9, status: 'completed', runAt: '2026-07-16', duration: '9m' }],
    performanceTrend: trend(75, 12, 3),
    intelligenceCard: {
      strengths: ['10M token context', 'Very low cost', 'Fast inference'],
      weaknesses: ['Less capable than Maverick', 'Requires GPU infrastructure'],
      bestUseCases: ['Document indexing', 'Long-context retrieval', 'Lightweight chat'],
      avoidFor: ['Complex reasoning', 'Frontier-level performance requirements'],
    },
    defaultTemperature: 0.6, defaultTopP: 0.9, defaultMaxTokens: 4096,
  },

  // ── Mistral AI ───────────────────────────────────────────────────────────
  {
    id: 'mistral-large-2',
    name: 'Mistral Large 2',
    provider: 'Mistral AI',
    family: 'Mistral',
    version: '2407',
    description: 'European frontier model with strong multilingual and coding capabilities.',
    architecture: 'Transformer',
    tokenizer: 'SentencePiece',
    parameterCount: '~123B',
    contextWindow: 128000,
    modalities: ['text', 'code'],
    capabilityTags: ['Chat', 'Tool Calling', 'Code', 'Function Calling', 'Streaming', 'Fine-tunable'],
    status: 'active',
    license: 'Custom',
    releaseDate: '2024-07-24',
    registeredAt: '2024-07-25T09:00:00Z',
    lastEvaluated: '2026-07-17T10:00:00Z',
    overallScore: 82.1,
    latencyMs: 760,
    evaluationCount: 23,
    profile: { modelId: 'mistral-large-2', profileVersion: '1.1', taxonomyVersion: '1.0', capabilities: caps([82, 80, 74, 75, 0, 86, 79, 82]) },
    health: { availability: 99.2, reliability: 98.9, errorRate: 1.1, responseQuality: 86, status: 'healthy', lastChecked: '2026-07-22T08:00:00Z' },
    cost: { inputPer1kTokens: 0.002, outputPer1kTokens: 0.006, averageCostPerCall: 0.005, monthlyEstimate: 140, projectedMonthly: 160, currency: 'USD' },
    deployment: { status: 'deployed', endpoint: 'https://api.mistral.ai/v1', region: 'eu-west-1', runtime: 'Mistral API', provider: 'Mistral AI' },
    versions: [{ version: '2407', name: 'Mistral Large 2', releaseDate: '2024-07-24', changes: 'Initial large 2 release', isLatest: true, isCurrent: true }],
    benchmarkScores: [
      { benchmarkId: 'mmlu', benchmarkName: 'MMLU', category: 'knowledge', score: 84.0, percentile: 76, evaluatedAt: '2026-07-17', runId: 'run-090' },
    ],
    evaluationHistory: [{ id: 'eh-090', benchmarkName: 'MMLU', score: 84.0, status: 'completed', runAt: '2026-07-17', duration: '10m' }],
    performanceTrend: trend(78, 12, 3),
    intelligenceCard: {
      strengths: ['GDPR-compliant EU hosting', 'Strong multilingual', 'Fine-tunable'],
      weaknesses: ['No vision', 'Less capable than frontier models on complex tasks'],
      bestUseCases: ['Multilingual applications', 'European compliance', 'Code assistance'],
      avoidFor: ['Vision tasks', 'Cutting-edge reasoning benchmarks'],
    },
    defaultTemperature: 0.7, defaultTopP: 1.0, defaultMaxTokens: 4096,
  },
  // ── xAI ─────────────────────────────────────────────────────────────────
  {
    id: 'grok-3',
    name: 'Grok 3',
    provider: 'xAI',
    family: 'Grok',
    version: '2025-02',
    description: 'xAI flagship with strong reasoning and real-time data access.',
    architecture: 'Transformer',
    tokenizer: 'Custom BPE',
    parameterCount: '~314B (est.)',
    contextWindow: 131072,
    modalities: ['text', 'vision', 'code'],
    capabilityTags: ['Chat', 'Vision', 'Reasoning', 'Code', 'Streaming'],
    status: 'active',
    license: 'Proprietary',
    releaseDate: '2025-02-17',
    registeredAt: '2025-02-18T09:00:00Z',
    lastEvaluated: '2026-07-15T10:00:00Z',
    overallScore: 88.9,
    latencyMs: 870,
    evaluationCount: 22,
    profile: { modelId: 'grok-3', profileVersion: '1.0', taxonomyVersion: '1.0', capabilities: caps([87, 89, 88, 80, 78, 85, 82, 76]) },
    health: { availability: 98.8, reliability: 98.4, errorRate: 1.6, responseQuality: 91, status: 'healthy', lastChecked: '2026-07-22T08:00:00Z' },
    cost: { inputPer1kTokens: 0.003, outputPer1kTokens: 0.015, averageCostPerCall: 0.01, monthlyEstimate: 280, projectedMonthly: 310, currency: 'USD' },
    deployment: { status: 'deployed', endpoint: 'https://api.x.ai/v1', region: 'global', runtime: 'xAI API', provider: 'xAI' },
    versions: [{ version: '2025-02', name: 'Grok 3', releaseDate: '2025-02-17', changes: 'Initial release', isLatest: true, isCurrent: true }],
    benchmarkScores: [
      { benchmarkId: 'mmlu', benchmarkName: 'MMLU', category: 'knowledge', score: 87.3, percentile: 87, evaluatedAt: '2026-07-15', runId: 'run-100' },
    ],
    evaluationHistory: [{ id: 'eh-100', benchmarkName: 'MMLU', score: 87.3, status: 'completed', runAt: '2026-07-15', duration: '11m' }],
    performanceTrend: trend(84, 12, 3),
    intelligenceCard: {
      strengths: ['Strong reasoning', 'Web search integration', 'Competitive benchmark performance'],
      weaknesses: ['Smaller ecosystem', 'Less tool integrations'],
      bestUseCases: ['Research queries', 'Reasoning tasks', 'Real-time info retrieval'],
      avoidFor: ['Established API ecosystem parity tasks'],
    },
    defaultTemperature: 1.0, defaultTopP: 1.0, defaultMaxTokens: 8192,
  },
  // ── DeepSeek ─────────────────────────────────────────────────────────────
  {
    id: 'deepseek-r2',
    name: 'DeepSeek R2',
    provider: 'DeepSeek',
    family: 'DeepSeek',
    version: '2025-05',
    description: 'Open-source reasoning model with chain-of-thought and strong math performance.',
    architecture: 'MoE Transformer',
    tokenizer: 'BPE',
    parameterCount: '~671B MoE',
    contextWindow: 163840,
    modalities: ['text', 'code'],
    capabilityTags: ['Chat', 'Reasoning', 'Code', 'Streaming', 'Fine-tunable'],
    status: 'active',
    license: 'Custom',
    releaseDate: '2025-05-01',
    registeredAt: '2025-05-02T09:00:00Z',
    lastEvaluated: '2026-07-18T10:00:00Z',
    overallScore: 91.7,
    latencyMs: 1240,
    evaluationCount: 19,
    profile: { modelId: 'deepseek-r2', profileVersion: '1.0', taxonomyVersion: '1.0', capabilities: caps([93, 94, 96, 80, 0, 78, 82, 64]) },
    health: { availability: 97.5, reliability: 97.1, errorRate: 2.9, responseQuality: 92, status: 'degraded', lastChecked: '2026-07-22T08:00:00Z' },
    cost: { inputPer1kTokens: 0.00055, outputPer1kTokens: 0.00219, averageCostPerCall: 0.002, monthlyEstimate: 95, projectedMonthly: 110, currency: 'USD' },
    deployment: { status: 'deployed', endpoint: 'https://api.deepseek.com/v1', region: 'global', runtime: 'DeepSeek API', provider: 'DeepSeek' },
    versions: [{ version: '2025-05', name: 'DeepSeek R2', releaseDate: '2025-05-01', changes: 'Initial release', isLatest: true, isCurrent: true }],
    benchmarkScores: [
      { benchmarkId: 'mmlu', benchmarkName: 'MMLU', category: 'knowledge', score: 88.5, percentile: 90, evaluatedAt: '2026-07-18', runId: 'run-110' },
      { benchmarkId: 'gsm8k', benchmarkName: 'GSM8K', category: 'mathematics', score: 97.3, percentile: 99, evaluatedAt: '2026-07-18', runId: 'run-111' },
    ],
    evaluationHistory: [{ id: 'eh-110', benchmarkName: 'MMLU', score: 88.5, status: 'completed', runAt: '2026-07-18', duration: '14m' }],
    performanceTrend: trend(87, 12, 3),
    intelligenceCard: {
      strengths: ['Best-in-class math', 'Exceptional reasoning via CoT', 'Cost-efficient vs frontier'],
      weaknesses: ['No vision', 'Higher latency due to thinking', 'Data privacy concerns for some orgs'],
      bestUseCases: ['Math & science research', 'Complex code reasoning', 'Theorem proving'],
      avoidFor: ['Real-time applications', 'Vision tasks', 'Privacy-sensitive enterprise data'],
    },
    defaultTemperature: 0.0, defaultTopP: 1.0, defaultMaxTokens: 8096,
  },
];

/* ----------------------------------------------------------------------- */
/*  Legacy compatibility alias (used by Research page + CapabilitySnapshot) */
/* ----------------------------------------------------------------------- */
export const AI_MODELS = MOCK_MODELS;
