import json
import os
import sys

registry_path = 'D:/atlas/results/experiments/registry.json'
experiments_dir = 'D:/atlas/results/experiments'
output_file = 'D:/atlas/llm_responses_round1.md'

try:
    with open(registry_path, encoding='utf-8') as f:
        registry = json.load(f)
except Exception as e:
    print(f"Failed to load registry: {e}")
    sys.exit(1)

# We want all experiments with total_tasks == 2
# Let's sort them by dataset, then provider, then model
round1_exps = [e for e in registry if e.get('total_tasks') == 2]
round1_exps.sort(key=lambda x: (x.get('dataset', ''), x.get('config', {}).get('provider', ''), x.get('model', '')))

with open(output_file, 'w', encoding='utf-8') as out:
    out.write("# LLM Benchmarking Round 1 Responses\n\n")
    out.write("This document contains the raw responses generated by the LLMs for the 2-question benchmark (Round 1).\n\n")
    
    current_dataset = None
    
    for exp in round1_exps:
        ds = exp.get('dataset', 'Unknown Dataset')
        provider = exp.get('config', {}).get('provider', 'Unknown Provider')
        model = exp.get('model', 'Unknown Model')
        exp_id = exp.get('id')
        pass_ratio = exp.get('pass_at_1', 0)
        
        if ds != current_dataset:
            current_dataset = ds
            out.write(f"## Dataset: {ds.upper()}\n\n")
            
        out.write(f"### {provider} | {model} (Pass Rate: {pass_ratio*100:.0f}%)\n\n")
        
        tasks_dir = os.path.join(experiments_dir, exp_id, 'tasks')
        
        if not os.path.exists(tasks_dir):
            out.write("*No task responses recorded for this run. Error or execution failure during the run.*\n\n")
            continue
            
        task_files = sorted([f for f in os.listdir(tasks_dir) if f.endswith('.json')])
        if not task_files:
            out.write(f"*No task files found in {tasks_dir}.*\n\n")
            continue
            
        for t_file in task_files:
            t_path = os.path.join(tasks_dir, t_file)
            try:
                with open(t_path, encoding='utf-8') as tf:
                    t_data = json.load(tf)
                
                task_id = t_data.get('task_id', t_file)
                prompt = t_data.get('prompt', 'No prompt recorded')
                response = t_data.get('raw_response', 'No response recorded')
                success = (t_data.get('status') == 'PASS') or t_data.get('success', False)
                error = t_data.get('error_message') or t_data.get('error')
                
                status_icon = "✅" if success else "❌"
                
                out.write(f"#### Task: {task_id} {status_icon}\n")
                
                if error:
                    out.write(f"**Error:** `{error}`\n\n")
                
                out.write("**Raw LLM Response:**\n")
                out.write("```python\n")
                out.write(response.strip() if response else "")
                out.write("\n```\n\n")
                
            except Exception as e:
                out.write(f"*Failed to read {t_file}: {e}*\n\n")
                
        out.write("---\n\n")

print(f"Generated response report at {output_file}")
